name: 'Setup MySQL'
description: 'Setup a MySQL database'
author: 'Mirro Mutth'
branding:
  icon: 'database'
  color: 'orange'
inputs:
  host port:
    description: 'The port of host'
    required: false
    default: 3306
  container port:
    description: 'The port of container'
    required: false
    default: 3306
  character set server:
    description: '--character-set-server - The character set of MySQL server'
    required: false
    default: 'utf8mb4'
  collation server:
    description: '--collation-server - The character collation of MySQL server'
    required: false
    default: 'utf8mb4_general_ci'
  mysql variant:
    description: 'Variant (fork) of MySQL. Values: mysql, mariadb.'
    required: false
    default: 'mysql'
  mysql version:
    description: 'Version of MySQL to use'
    required: false
    default: 'latest'
  mysql root password:
    description: 'MYSQL_ROOT_PASSWORD - root superuser password'
    required: false
    default: ''
  mysql database:
    description: 'MYSQL_DATABASE - name for the default database that is created'
    required: false
    default: ''
  mysql user:
    description: 'MYSQL_USER - create the specified user with superuser power for created database'
    required: false
    default: ''
  mysql password:
    description: 'MYSQL_PASSWORD - specified superuser password which user is power for created database'
    required: false
    default: ''
  authentication plugin:
    description: 'Set authentication plugin. Login/password is used as default. Changes default behaviour of MySQL 8.0+, where `caching_sha2_password` is a default value.'
    required: false
    default: 'mysql_native_password'
runs:
  using: 'docker'
  image: 'Dockerfile'
